[package]
name = "wikia_api"
version = "0.1.0"
authors = ["Dhs92 <forehand.alex@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
reqwest = "0.9.15"
serde_json = "1.0.39"
serde = { version = "1.0.90", features = ["derive"] }
url = "1.7.2"
